### PR TITLE
test: add enforcer react-native test

### PR DESCRIPTION
**Pull request by Shivansh-yadav13**
- test is not added rn, going to add
Signed-off-by: Shivansh-yadav13 <yadavshivansh@gmail.com>

### CODE REVIEW

**Comment by Shivansh-yadav13** [comment]
@Zxilly @nodece pls review

**Review by nodece — APPROVED** [review]

**Comment by nodece** [comment]
You also need to add a workflow for this PR

**Comment by Shivansh-yadav13** [comment]
@nodece @Zxilly how can I fix this error? pls help

**Comment by nodece** [comment]
Please check CI.

**Comment by Shivansh-yadav13** [comment]
@nodece IG symlink does not work in react-native, maybe I should try https://github.com/callstack/repack
what do you think?

**Comment by Shivansh-yadav13** [comment]
for some reason cannot install the testing library and cannot find the solution anywhere, I have opened an issue in the testing-library github
```
npm ERR! code ERESOLVE
npm ERR! ERESOLVE unable to resolve dependency tree
npm ERR! 
npm ERR! While resolving: reactnative@1.0.0
npm ERR! Found: react@17.0.2
npm ERR! node_modules/react
npm ERR!   react@"17.0.2" from the root project
npm ERR!   peer react@">=16.0.0" from @testing-library/react-native@10.1.1
npm ERR!   node_modules/@testing-library/react-native
npm ERR!     dev @testing-library/react-native@"*" from the root project
npm ERR!   1 more (react-native)
npm ERR! 
npm ERR! Could not resolve dependency:
npm ERR! peer react@"^18.2.0" from react-test-renderer@18.2.0
npm ERR! node_modules/react-test-renderer
npm ERR!   peer react-test-renderer@">=16.0.0" from @testing-library/react-native@10.1.1
npm ERR!   node_modules/@testing-library/react-native
npm ERR!     dev @testing-library/react-native@"*" from the root project
npm ERR! 
npm ERR! Fix the upstream dependency conflict, or retry
npm ERR! this command with --force, or --legacy-peer-deps
npm ERR! to accept an incorrect (and potentially broken) dependency resolution.
npm ERR! 
npm ERR! See /home/shivansh/.npm/eresolve-report.txt for a full report.

npm ERR! A complete log of this run can be found in:
npm ERR!     /home/shivansh/.npm/_logs/2022-06-28T11_36_31_247Z-debug-0.log
```

**Comment by nodece** [comment]
I remember the react-native with test library, you don't need to re-install a test library, link to https://reactnative.dev/docs/testing-overview.

BTW, you should use Yarn instead of NPM.

**Pull request merged**
